name: pr / testing / bash

on: 
  pull_request:
    branches:
    - master
    paths:
    - 'entrypoint.sh'
    - 'actions/*.sh'
    - 'lib/*.bash'
    - 'lib/**/*.bash'
    - 'tests/*.bats'
    - 'tests/**/*.bats'

jobs:
  bats:
    runs-on: ubuntu-latest

    steps:
    - name: Setup BATS
      id: setup-bats
      uses: mig4/setup-bats@v1.0.1
      with:
        bats-version: 1.1.0

    - name: Checkout Source
      id: checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Git Config
      id: git-config
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "Github Actions"

    - name: BATS testing
      id: bats-testing
      run: bats -r tests/
