name: pr / results / files_changed / actions
on:
  repository_dispatch:
    types: [ dependency_update_workflow ]
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Parse Actions
        id: parse-actions
        run: |
          echo "::debug filename=pr-test-rd-resp.yaml,line=12::KO_ACTIONS=$(echo -n "${KO_ACTIONS}")"

          KO_ACTIONS=$(echo -n "${KO_ACTIONS}")
          echo "::debug filename=pr-test-rd-resp.yaml,line=15::$(echo -n "${KO_ACTIONS}" | jq .)"

          KO_ALL=$(echo -n "${KO_ACTIONS}" | jq .all)
          echo "::debug filename=pr-test-rd-resp.yaml,line=18::KO_ALL=${KO_ALL}"
          echo "::set-output name=all::${KO_ALL}"

          KO_NEW=$(echo -n "${KO_ACTIONS}" | jq .new)
          echo "::debug filename=pr-test-rd-resp.yaml,line=22::KO_NEW=${KO_NEW}"
          echo "::set-output name=new::${KO_NEW}"

          KO_UPDATED=$(echo -n "${KO_ACTIONS}" | jq .updated)
          echo "::debug filename=pr-test-rd-resp.yaml,line=26::KO_UPDATED=${KO_UPDATED}"
          echo "::set-output name=updated::${KO_UPDATED}"

          KO_REMOVED=$(echo -n "${KO_ACTIONS}" | jq .removed)
          echo "::debug filename=pr-test-rd-resp.yaml,line=30::KO_REMOVED=${KO_REMOVED}"
          echo "::set-output name=removed::${KO_REMOVED}"
        env:
          KO_ACTIONS: ${{ toJson(github.event.client_payload.actions) }}
      - name: All Actions
        id: all-actions
        if: steps.parse-actions.outputs.all
        run: |
          echo "All Impacted Actions: ${KO_ACTIONS}"
        env:
          KO_ACTIONS: "${{ steps.parse-actions.outputs.all }}"

      - name: New Actions
        id: new-actions
        if: steps.parse-actions.outputs.new
        run: |
          echo "New Actions: ${KO_ACTIONS}"
        env:
          KO_ACTIONS: "${{ steps.parse-actions.outputs.new }}"

      - name: Updated Actions
        id: updated-actions
        if: steps.parse-actions.outputs.updated
        run: |
          echo "Updated Actions: ${KO_ACTIONS}"
        env:
          KO_ACTIONS: "${{ steps.parse-actions.outputs.updated }}"

      - name: Removed Actions
        id: removed-actions
        if: steps.parse-actions.outputs.removed
        run: |
          echo "Removed Actions: ${KO_ACTIONS}"
        env:
          KO_ACTIONS: "${{ steps.parse-actions.outputs.removed }}"
